### ISSUE TITLE
Can not validate UBL

### ISSUE THREAD

**Issue by SemyonSoldatenko** [ramonwirsch/fopRenderer#1]
Can not validate UBL. Reporting error:
```
> unknown protocol: urn
````
Configuration fragment
```groovy
fopRenderer {
    schemas {
        schemaUBL {
            files = file('tmp.xml')
            schemaUri = 'urn:oasis:names:specification:ubl:schema:xsd:Invoice-2'
            offlineSchema = file('schemas/maindoc/UBL-Invoice-2.0.xsd')
        }
    }
...
```

**Comment by SemyonSoldatenko** [comment]
My mistake.
I should be used this:
`schemaUri = 'https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/maindoc/UBL-Invoice-2.0.xsd'` 
it works.

p.s.`offlineSchema` setting works only with `-PofflineSchemas=true`

**Comment by ramonwirsch** [comment]
Hi,
so I just looked into it and this error occurs because internally URL is used everywhere and the setter setSchemaUri(String) just uses URL(string). The Java SAX stuff that is utilized internally only supports URL instances, because it attempts to actually load it.

If you can point me to an example how URNs can be used with SAX, I'll try to incorporate it into the plugin, but as of now it is not supported.

-- so I guess it doesn't matter now

**Comment by ramonwirsch** [comment]
The code I wrote for 'offline' should also check gradles --offline flag, but it has no builtin timeout.

Did the --offline flag actually not work for you? Then please provide me your gradle version, and I'll try to investigate further...

**Comment by SemyonSoldatenko** [comment]
I was mislead by names `schemaUri` and `offileSchema`. I thought it is target namespace and xsd location.
But actually it is two different settings, one to work online and another one to work offline.

Now I've provided online url to fetch xsd, and local xsd files to use in offline mode, and it works:
```
schemas {
    InvoiceUBL20 {
        files = fileTree(dir: 'xml/invoices', include: '*.xml')
        schemaUri = 'https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/maindoc/UBL-Invoice-2.0.xsd'
        offlineSchema = file('schemas/maindoc/UBL-Invoice-2.0.xsd')
    }
...
```
✅ It works:

Validate against online xsd files.
`./gradlew validate`

Validate against local xsd files.
`./gradlew validate --offline`
`./gradlew validate -PofflineSchemas=true`

My gradle version
```
$ ./gradlew -v

------------------------------------------------------------
Gradle 3.0
------------------------------------------------------------

Build time:   2016-08-15 13:15:01 UTC
Revision:     ad76ba00f59ecb287bd3c037bd25fc3df13ca558

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Mac OS X 10.12.5 x86_64
```

Thank you for your work.
