### ISSUE TITLE
Upgrade Apache FOP dependency to version 2.6

### ISSUE THREAD

**Issue by vjlamp** [ramonwirsch/fopRenderer#7]
Currently this project depends on FOP 1.1. Many improvements were delivered since. FOP 2.6 is the current release.

**Comment by ramonwirsch** [comment]
Did no really follow developments, since my personal use case ended, but I will give it a look.

**Comment by ramonwirsch** [comment]
Change was easy, commit is up and release under 0.4.0 is in progress

**Comment by ramonwirsch** [comment]
Version 0.4.0 has been published

**Comment by vjlamp** [comment]
All is working well. Thank you for taking the time to make the dependency upgrade.
